flowchart TB
 subgraph "Rede Interna Monitoreada"
  Attacker[Atacante<br>Debian 12] -- "Ataques (tráfico malicioso)" --> Victim[Vítima<br>Debian 12]
  SecurityOnion[Security Onion<br>Debian 12] -- "Interface de sensor en modo promiscuo" --> Attacker
  SecurityOnion -- "Interface de sensor en modo promiscuo" --> Victim
 end
 SecurityOnion --- Host[(Host físico<br/>VirtualBox)]
 SecurityOnion -- "Interface de xestión<br/>(acceso a Kibana, actualizacións)" --- Host
