graph TD;
    A["VIPER Server (C2)<br>VM-1"] -->|Comando e Control| B["VM-2"];
    B -->|Movemento Lateral| C["VM-3"];
    C -->|Exfiltración de Datos| A;
    
    
style A fill:yellow,stroke:#333,stroke-width:2px;
style B fill:red,stroke:#333,stroke-width:2px;
style C fill:violet,stroke:#333,stroke-width:2px;
