graph TD;
    subgraph "Rede Virtual"
        A[VM Atacante Debian 12 Viper C2 Server];
        B[VM Vítima Debian 12]; 
    end  
 
    B -- "(1) Payload" --> A;
    A -- "(2) Envío de Comandos" --> B;
    B -- "(3) Devolución de Resultados" --> A;
 
    style A fill:yellow,stroke:#333,stroke-width:2px;
    style B fill:red,stroke:#333,stroke-width:2px;
